

angular.module('AduguShopApp').filter('myTranslator', function() {
	return function (id, lang){
		return dict[lang][id];
	}
});

var dict = {
	hu:{
		'and': 'and',
		'or': 'or',
		'okay': 'Okay',
		'add-to-basket': 'Add To Basket',
		'out-of-stock': 'Out of stock',
		'added-to-basket': 'Item has been added to basket',
		'description': 'Product Description',
		'delivery': 'Delivery',
		'returns': 'Returns',
		'stairs': 'Stairs',
		'ramps': 'Ramps',
		'customer-photos': 'Customer Photos',
		'more': 'More',
		'title-home': 'Dome Kutya | Dog Stairs and Ramps Shop',
		'close': 'Close',
		'about-us': 'About Us',
		'settings': 'Settings',
		'contact': 'Contact',
		'contact-us': 'Contact Us',
		'use-of-personal-data': 'Use of personal data',
		'legal-information': 'Legal Information',
		'contact-for-more': 'Contact us for pricing',
		'invalid-text': 'Invalid text or empty',
		'your-basket': 'Your Basket',
		'basket-is-empty': 'Your basket is empty',
		'choose-country': 'choose country',
		'hungary': 'Hungary',
		'germany': 'Germany',
		'italy':'Italy',
		'switzerland': 'Switzerland',
		'romania':'Romania',
		'france':'France',
		'united kingdom': 'United Kingdom',
		'choose-courier': 'Choose Courier',
		'remove': 'Remove',
		'subtotal': 'Subtotal',
		'total': 'Total',
		'proceed-to-payment': 'Proceed To Payment',
		'cookie-settings': 'Cookie Settings',
		'contact-info': 'Contact Information',
		'full-name': 'Full Name',
		'dogs-name': "Your dog's name",
		'email': 'email address',
		'telephone': 'Telephone Number',
		'delivery-information': 'Delivery Information',
		'address': 'Your address line',
		'postcode': 'Post Code',
		'city': 'City',
		'required': 'Required',
		'order-review': 'Review',
		'quantity': 'Quantity',
		'deliver-to': 'Deliver To',
		'comments': 'Comments',
		'max-length': 'Maximum Length',
		'bank-transfer': 'Bank Transfer',
		'pay-on-delivery': 'Pay On Delivery',
		'order-confirmation': 'Order Confirmation'

	},
	en:{
		'and': 'és',
		'or': 'vagy',
		'okay': 'Rendben',
		'add-to-basket': 'Kosárba rakom',
		'out-of-stock': 'Nincs készlete',
		'added-to-basket': 'A termék a kosaradba került',
		'description': 'Leírás',
		'delivery': 'Szállítás',
		'returns': 'Áruvisszaküldés',
		'stairs': 'Lépcsők',
		'ramps': 'Rámpák',
		'customer-photos': 'Vásárlói képek',
		'more': 'Több',
		'title-home': 'Dome Kutya | Kutya lépcso és rámpa web uszlet',
		'close': 'Bezárt',
		'about-us': 'Rólunk',
		'settings': 'Beállítások',
		'contact': 'Kapcsolat',
		'contact-us': 'Lépjen kapcsolatba velünk',
		'use-of-personal-data': 'Adatvédelmi nyilatkozat',
		'legal-information': 'Általános szerződési feltételek',
		'contact-for-pricing': 'Lépjen kapcsolatba velünk',
		'invalid-text': 'Érvénytelen szöveg',
		'your-basket': 'Kosár',
		'basket-is-empty': 'Az Ön kosara üres',
		'choose-country': 'Válasszon országot a szállítási költség kalkulálásához',
		'hungary': 'Magyarország',
		'germany': 'Németország',
		'italy':'Olaszország',
		'switzerland': 'Svájc',
		'romania':'Románia',
		'france':'Franciaország',
		'united kingdom': 'Egyesült Királyság',
		'choose-courier': 'Válasszon futárt',
		'remove': 'Eltávolít',
		'subtotal': 'Részösszeg',
		'total': 'Végösszeg',
		'proceed-to-payment': 'Tovább a fizetéshez',
		'cookie-settings': 'Sütik beállítása(Cookie)',
		'required': 'Megadása szükséges',
		'contact-info': 'Elérhetőség',
		'full-name': 'Név',
		'dogs-name': "A kutyád neve",
		'email': 'Email cím',
		'telephone': 'Telefonszám',
		'delivery-information': 'Szállítási információk',
		'address': 'Szállítási cím',
		'postcode': 'Irányítószám',
		'city': 'Város',
		'order-review': 'A kosár tartalma',
		'quantity': 'Mennyiség',
		'deliver-to': 'Címzett',
		'comments': 'Megjegyzés',
		'max-length': 'Maximális hossz',
		'bank-transfer': 'Banki átutalás',
		'pay-on-delivery': 'Utánvétes fizetés',
		'order-confirmation': 'Rendelés megerősítése'
	}
}
  